# Generated by Django 3.1.3 on 2022-01-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('candidate_ref', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('score', models.FloatField(primary_key=True, serialize=False)),
                ('candidate_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='myapi.candidate')),
            ],
        ),
    ]
